import { Button } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser } from "@fortawesome/free-solid-svg-icons";
import { useNavigate, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { Url } from "../App";
import BaseApp from "../BaseApp/Base";



export default function ContactView(){
    const navigate = useNavigate();
    const {id} = useParams();
    const token = sessionStorage.getItem('token') 
    const [contact,setContact] = useState([]);

    useEffect(()=>{
        const getData = async()=>{
            try{
                const EmpResponse = await axios.get(`${Url}/Contacts/${id}`,{
                    headers:{
                        "Content-Type":"application/json",
                        "Authorization" : `Bearer ${token}`
                    }
                })
                setContact([EmpResponse.data.Contact])
                //console.log(EmpResponse.data)
                toast.success(EmpResponse.data.message)
            }
            catch(err){
                toast.error(err.response.data.message)
            }
        }
        getData();
    },[])

    return(
        <BaseApp PageTitle="Contact Detailed View">
            <div className="view-mainCon">
                {contact.map((per,idx)=>(
                    <div className="view-user" key={idx}>
                        <p><b>Lead Data</b></p>
                        <p>Contact Id : {per._id}</p>
                        <p>First_Name : {per.First_Name}</p>
                        <p>Last Name : {per.Last_Name}</p>
                        <p>Email Id : <a href={`mailto:${per.Email}`}>{per.Email}</a></p>

                        <p><b>Contact Generated By</b></p>
                        <label>Employee Id : {per.Contact_Generated_by}</label><hr/>
                        <div className="view-stu-btn">
                            <Button onClick={()=>navigate(`/Contacts/changeToLead/${per.Email}`)}><FontAwesomeIcon icon={faUser} />{" "}Promote as Lead</Button>{" "}
                            <hr/>
                            <Button onClick={()=>navigate("/Contacts")}><FontAwesomeIcon icon={faUser} />{" "}Back to Contact Data</Button>
                        </div>
                    </div>
                ))}
            </div>
        </BaseApp>
    );
}