import { Button } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser } from "@fortawesome/free-solid-svg-icons";
import { useNavigate, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { Url } from "../App";
import BaseApp from "../BaseApp/Base";



export default function LeadView(){
    const navigate = useNavigate();
    const {id} = useParams();
    const token = sessionStorage.getItem('token') 
    const [lead,setLead] = useState([]);
    const [service,setService] = useState([]);

    useEffect(()=>{
        const getData = async()=>{
            try{
                const EmpResponse = await axios.get(`${Url}/Lead/${id}`,{
                    headers:{
                        "Content-Type":"application/json",
                        "Authorization" : `Bearer ${token}`
                    }
                })
                setLead([EmpResponse.data.Lead])
                setService(EmpResponse.data.Lead.Service_Requests)
                //console.log(EmpResponse.data)
                toast.success(EmpResponse.data.message)
            }
            catch(err){
                toast.error(err.response.data.message)
            }
        }
        getData();
    },[])

    return(
        <BaseApp PageTitle="Lead Detailed View">
            <div className="view-mainCon">
                {lead.map((per,idx)=>(
                    <div className="view-user" key={idx}>
                        <p><b>Lead Data</b></p>
                        <p>Lead Id : {per._id}</p>
                        <p>First_Name : {per.First_Name}</p>
                        <p>Last Name : {per.Last_Name}</p>
                        <p>Email Id : <a href={`mailto:${per.Email}`}>{per.Email}</a></p>
                        <p>Status : {per.Status}</p>
                        <p><b>Leads Generated By</b></p>
                        <label>Employee Id : {per.Lead_Generated_by}</label>
                        <p><b>Service Requests</b></p>
                        {service.map((ser,inds)=>(
                            <p key={inds}>Id : {ser},{" "}</p>
                        ))}
                        <div className="view-stu-btn">
                            <Button onClick={()=>navigate("/Lead/LeadData")}><FontAwesomeIcon icon={faUser} />{" "}Back to Lead Data</Button>
                        </div>
                    </div>
                ))}
            </div>
        </BaseApp>
    );
}